#!/bin/sh
### BEGIN INIT INFO
# Provides:          svn_serve
# Required-Start:    $all
# Required-Stop:     $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the oraynewph
### END INIT INFO

case $1 in

start)
	/usr/oray-app/bin/oraynewph -s 0.0.0.0  &
	/usr/oray-app/bin/oraysl  -a 127.0.0.1 -p 16062 -s phsle01.oray.net:80 -d
	;;
stop)
	killall oraynewph
	killall oraysl
	;;
*)
echo "Usage: $0 (start|stop)"
;;

esac
